[package]
name = "tas_v2"
description = "TasV2 Tremolo Audio Plug-in"
version = "0.0.1"
authors = ["Pedro Tacla Yamada <tacla.yamada@gmail.com>"]
edition = "2018"
homepage = "https://github.com/yamadapc/augmented-audio"
repository = "https://github.com/yamadapc/augmented-audio"
license = "MIT"

[dependencies]
vst = { path = "../../vendor/vst" }
crossbeam = "^0.8.0"
env_logger = "0.9.0"
log = "^0.4.11"
serde = { version = "^1.0.126", features = ["derive"] }
dirs = "4.0"
log4rs = { version = "^1.0.0", features = ["rolling_file_appender", "compound_policy", "size_trigger"] }
futures-util = "^0.3.15"
serde_json = "^1.0.64"
tungstenite = "^0.13.0"
async-trait = "^0.1.50"
thiserror = "^1.0.25"

webview-transport = { path = "../../augmented/gui/webview-transport" }
audio-parameter-store = { path = "../../augmented/audio/audio-parameter-store" }
audio-processor-standalone = { version = "1.0.0-alpha.13", path = "../../augmented/application/audio-processor-standalone" }
audio-garbage-collector = { version = "1.1.0", path = "../../augmented/audio/audio-garbage-collector" }
augmented_oscillator = { path = "../../augmented/audio/oscillator", version = "1.1.0" }
wisual-logger = { version = "^0.1", path = "../../augmented/ops/wisual-logger" }
generic-parameters-editor = { path = "../../augmented/gui/generic-parameters-editor" }
audio-processor-traits = { path = "../../augmented/audio/audio-processor-traits", version = "1.1.0" }

[target.'cfg(target_os = "macos")'.dependencies]
cacao = "0.3"
macos-bundle-resources = { path = "../../augmented/gui/macos-bundle-resources" }
webview-holder = { path = "../../augmented/gui/webview-holder" }
cocoa = "0.24.0"
objc = "0.2.7"
darwin-webkit = { version = "^0.1.3", path = "../../augmented/gui/darwin-webkit" }

[lib]
name = "tas_v2"
crate-type = ["lib", "cdylib"]

[package.metadata.augmented]
private = true

[package.metadata.bundle]
name = "TasV2"
identifier = "com.beijaflor.TasV2"

[package.metadata.bundle.macos.properties]
CFBundleGetInfoString = "vst"
