[package]
name = "wisual-logger"
version = "0.1.4"
authors = ["Pedro Tacla Yamada <tacla.yamada@gmail.com>"]
description = "Just a pretty printer configuration for `env_logger`"
license = "MIT"
edition = "2018"
repository = "https://github.com/yamadapc/augmented-audio"

[dependencies]
chrono = "0.4.19"
env_logger = "0.10.0"
log = "0.4.11"

[package.metadata.augmented]
