[package]
name = "augmented-adsr-envelope"
version = "0.1.0-alpha.2"
edition = "2018"
description = "ADSR envelope implementation"
license = "MIT"
homepage = "https://github.com/yamadapc/augmented-audio"
repository = "https://github.com/yamadapc/augmented-audio"

[dependencies]
augmented-atomics = { path = "../../data/atomics" }
num-traits = "0.2.14"
num-derive = "0.3.3"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
plotters = { version = "0.3" }

[package.metadata.augmented]
private = false
