[package]
name = "augmented-convert-sample-rate"
version = "1.0.0-alpha.3"
authors = ["yamadapc <tacla.yamada@gmail.com>"]
edition = "2018"
description = "Simplistic dev-quality implementation of audio sample-rate conversion."
license = "MIT"
homepage = "https://github.com/yamadapc/augmented-audio"
repository = "https://github.com/yamadapc/augmented-audio"

[dependencies]
samplerate = "0.2.4"

[dev-dependencies]
rand = "^0.8.3"
augmented_oscillator = { version = "1.0.0-alpha.3", path = "../../audio/oscillator" }
audio-processor-testing-helpers = { version = "1.0.0-alpha.4", path = "../../testing/audio-processor-testing-helpers" }

[package.metadata.augmented]
private = false
