[package]
name = "recording_buddy"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
# FFI
uniffi = "=0.15.2"
uniffi_macros = "=0.15.2"
anyhow = "=1.0.52" # https://github.com/mozilla/uniffi-rs/issues/1109

# macOS
objc = "0.2.7"
cocoa = "0.24.0"
metal = "0.23.1"
core-graphics-types = "0.1.1"
cty = "0.2.1"

# Augmented
log = "0.4"
plugin-host-lib = { path = "../../apps/plugin-host/plugin-host-lib" }
augmented = { path = "../../augmented/augmented" }
wisual-logger = { version = "0.1", path = "../../augmented/ops/wisual-logger" }

[build-dependencies]
uniffi_build = "=0.15.2"
uniffi_bindgen = "0.15.2"
cbindgen = "0.20.0"
