[package]
name = "plugin-host"
version = "0.1.0"
authors = ["yamadapc <tacla.yamada@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.0"

wisual-logger = { version = "0.1", path = "../../../augmented/ops/wisual-logger" }
plugin-host-lib = { path = "../plugin-host-lib" }
clap = "^2.33.3"
