[package]
name = "autosync-submodules"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "^3.0.0-beta.2"
log = "^0.4.14"
wisual-logger = { version = "^0.1.3", path = "../../augmented/ops/wisual-logger" }
cmd_lib = "^1.1.0"
serde_json = "^1.0"
serde = { version = "^1.0", features = [ "derive" ] }
