[package]
name = "augmented-analytics"
version = "0.1.0"
edition = "2018"

[dependencies]
async-trait = "0.1.51"
itertools = "0.10.1"
log = "0.4.14"
mockall = "0.10.2"
mockall_double = "0.2.0"
reqwest = "0.11.4"
serde = { version = "^1.0.126", features = ["derive"] }
serde_json = "^1.0.64"
serde_urlencoded = "0.7.0"
thiserror = "1.0.26"
tokio = { version = "1.10.0", features = ["rt-multi-thread", "rt", "macros"] }

[dev-dependencies]
wisual-logger = "0.1.3"
