[package]
name = "oscillator"
version = "0.1.0"
authors = ["yamadapc <tacla.yamada@gmail.com>"]
edition = "2018"
description = "Very simple implementation of an oscillator."

[dependencies]
cpal = { version = "^0.13.3" }

[dev-dependencies]
criterion = "^0.3"
ringbuf = "^0.2.6"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
plotters = { version = "0.3" }

[[bench]]
name = "sine_oscillator_benchmark"
harness = false
