[package]
name = "example-druid-audio-viz"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "^0.7.0"
instant = "^0.1.9"
basedrop = "^0.1.2"
log = "^0.4.14"

audio-processor-standalone = { path = "../../augmented/application/audio-processor-standalone" }
audio-garbage-collector = { path = "../../augmented/audio/audio-garbage-collector" }
atomic-queue = { path = "../../augmented/data/atomic-queue" }
circular-data-structures = { path = "../../augmented/data/circular-data-structures" }
audio-processor-traits = { version = "^0.3", path = "../../augmented/audio/audio-processor-traits" }