name: metronome
description: A simple metronome app

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.0-80.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^1.44.0
  graphx: ^1.0.4
  mobx: ^2.1.0
  flutter_mobx: ^2.0.6+4
  cupertino_icons: ^1.0.5
  sqflite: ^2.1.0
  floor: ^1.3.0
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  logger: ^1.1.0
  charts_flutter: ^0.12.0
  firebase_core: ^1.22.0
  firebase_analytics: ^9.3.5
  flutter_local_notifications: ^11.0.0
  timezone: ^0.9.0
  flutter_native_timezone: ^2.0.0
  ffi: ^2.0.1
  macos_ui: ^1.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  floor_generator: ^1.3.0
  build_runner: ^2.2.1
  mobx_codegen: ^2.0.7+3
  flutter_launcher_icons: ^0.10.0
  ffigen: ^6.1.2

flutter_icons:
  ios: "AppIcon"
  image_path: "design/icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true