name: metronome
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.0-80.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^1.9.1
  graphx: ^1.0.3
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.3+2
  cupertino_icons: ^1.0.2
  sqflite: ^2.0.1
  floor: ^1.2.0
  intl: ^0.17.0
  shared_preferences: ^2.0.11
  logger: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  floor_generator: ^1.2.0
  build_runner: ^2.1.2
  mobx_codegen: ^2.0.5+2

dependency_overrides:
  analyzer: ^3.0.0

flutter:
  uses-material-design: true