[package]
name = "augmented-dev-cli"
description = "CLI for augmented monorepo"
version = "0.1.0"
edition = "2018"
license = "MIT"
homepage = "https://github.com/yamadapc/augmented-audio"
repository = "https://github.com/yamadapc/augmented-audio"

[dependencies]
log = "0.4"
env_logger = "0.10.0"

itertools = "0.10"
anyhow = "1.0"
chrono = "0.4"
mockall = "0.11"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

clap = { version = "4.0", features = ["string"] }
cmd_lib = "1.3"

urlencoding = "2.1"
plist = "1.1"
time = "0.3.36"
crates_io_api = "0.8"
daggy = "0.8"
semver = "1.0"
rand = "0.8"

toml = "0.5"
toml_edit = "0.17"
sha3 = "0.10"
hex = "0.4"

[package.metadata.augmented]
private = true