[package]
name = "synth"
version = "0.1.0"
edition = "2018"
homepage = "https://github.com/yamadapc/augmented-audio"
repository = "https://github.com/yamadapc/augmented-audio"
license = "MIT"

[dependencies]
audio-garbage-collector = { version = "1.2.0", path = "../../augmented/audio/audio-garbage-collector" }
audio-processor-traits = { version = "4.3.0", path = "../../augmented/audio/audio-processor-traits" }
augmented-adsr-envelope = { path = "../../augmented/audio/adsr-envelope" , version = "0.5.0" }
augmented_oscillator = { version = "1.4.0", path = "../../augmented/audio/oscillator" }
audio-processor-standalone = { version = "3.5.0", path = "../../augmented/application/audio-processor-standalone" }
num = "^0.4.0"
rimd = "^0.0.1"
log = "^0.4.14"
wisual-logger = { version = "^0.1", path = "../../augmented/ops/wisual-logger" }
augmented-dsp-filters = { version = "2.5.0", path = "../../augmented/dsp/dsp-filters" }
pitch_calc = "^0.12.0"

[package.metadata.augmented]
private = true
