[package]
name = "ruas-bundler"
version = "0.1.0"
authors = ["yamadapc <tacla.yamada@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "^2.33.3"
log = "^0.4.14"
plist = "^1.1.0"
serde = { version = "^1.0.126", features = ["derive"] }
toml = "^0.5.8"
wisual-logger = "^0.1.2"
cmd_lib = "^1.1.0"