[package]
name = "augmented-dsp-filters"
version = "1.0.0-alpha.4"
edition = "2018"
description = "Audio filters (port of C++ DSPFilters)"
license = "MIT"
homepage = "https://github.com/yamadapc/augmented-audio"
repository = "https://github.com/yamadapc/augmented-audio"

[dependencies]
num = "^0.4.0"
audio-processor-traits = { version = "1.0.0-alpha.5", path = "../../audio/audio-processor-traits" }

[dev-dependencies]
audio-processor-testing-helpers = { version = "1.0.0-alpha.4", path = "../../testing/audio-processor-testing-helpers" }

[package.metadata.augmented]
private = false
